version: "3"
services:
    database:
      image: mysql:8.0
      restart: unless-stopped
      ports:
        - "9906:3306"
      command: '--default-authentication-plugin=mysql_native_password'
      networks:
        - app-network
      cap_add:
        - SYS_NICE 
      environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
      volumes:
          - "data:/var/lib/mysql"
          - ./sql:/docker-entrypoint-initdb.d

    php:
      depends_on:
        - database
      build: ./docker/php
      restart: unless-stopped
      volumes:
        - ./app:/var/www/html
        - ./docker/php/errors.ini:/usr/local/etc/php/conf.d/errors.ini
        - ./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
        - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      networks:
        - app-network

    webserver:
      depends_on:
        - php
      image: nginx:latest
      restart: unless-stopped
      ports:
        - "85:80"
      volumes:
        - ./app:/var/www/html
        - ./docker/nginx:/etc/nginx/conf.d
      networks:
        - app-network
volumes:
    data:
networks:
  app-network:
    driver: bridge  